name: Deploy de la paginación
on: 
  push: 
    branch:
      - main
jobs: 
  deploy-page:  
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name:
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build